name: Push Build

on:
  push:
    branches:
      - 'main'
      - 'automateVersionUpdate'

jobs:
  testVersionUpdate:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    concurrency: 
      group: ${{ github.head_ref || github.run_id }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3
      - name: Update Beam version
        id: beamable_updater
        uses: beamable/package-update-action@main
        with:
          project-path: "client"
      - name: Print the versions
        run: |
          echo "Local version is ${{ steps.beamable_updater.outputs.local_version }}"
          echo "Remote version is ${{ steps.beamable_updater.outputs.remote_version }}"
          echo "Did perform the update: ${{ steps.beamable_updater.outputs.did_perform_update }}"
      - name: Check if PR branch exists
        run: echo ::set-output name=any::$(if [ -n "$(git rev-parse --verify --quiet origin/beam${{ steps.beamable_updater.outputs.remote_version }})" ]; then echo "true"; else echo "false"; fi)
      - name: Create Pull Request
        if: ${{ steps.beamable_updater.outputs.did_perform_update }} && ${{ steps.format-changes.outputs.any == 'false' }}
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          add-paths: client/Packages
          branch: beam${{ steps.beamable_updater.outputs.remote_version }}
          title: 'Beamable update: ${{ steps.beamable_updater.outputs.remote_version }}'
          commit-message: 'Updated Beamable version to ${{ steps.beamable_updater.outputs.remote_version }}'


