name: PR Build

on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 90
    concurrency: 
      group: ${{ github.head_ref || github.run_id }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            client/Library
            client/Temp
            client/obj
          key: Library-WebGL
      - name: Get Beam version
        id: beamable_updater
        uses: beamable/package-update-action@main
        with:
          dry-run: true
          project-path: "client"
      - name: Build WebGL client
        id: build
        uses: game-ci/unity-builder@v2.0.4
        env:
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL
          projectPath: "client"
          allowDirtyBuild: true
          buildsPath: dist
          versioning: Custom
          version: ${{ steps.beamable_updater.outputs.local_version }}
          buildMethod: Beamable.Editor.BuildScript.Build
      - uses: actions/upload-artifact@v3
        with:
          name: Build-WebGL
          path: ./dist/WebGL
      - uses: github-actions-up-and-running/pr-comment@v1.0.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          message: Built successfully my friend!
